# Generated by Django 4.2.4 on 2023-09-14 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_checker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 9, 8, 44, 91876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
